[package]
name = "ckb-debugger-api"
description = "Standalone debugger for Nervos CKB"
version = "0.110.0"
license = "MIT"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
ckb-hash = { git = "https://github.com/nervosnetwork/ckb" }
ckb-chain-spec = { git = "https://github.com/nervosnetwork/ckb" }
ckb-jsonrpc-types = { git = "https://github.com/nervosnetwork/ckb" }
ckb-mock-tx-types = { path = "../ckb-mock-tx-types" }
ckb-script = { git = "https://github.com/nervosnetwork/ckb", default-features = false }
ckb-types = { git = "https://github.com/nervosnetwork/ckb" }
ckb-vm = { version = "=0.24.0" }
faster-hex = "0.4.0"
hex = "0.4"
js-sys = "0.3.27"
regex = "1"
serde = { version="1.0", features = ["derive"] }
serde_json = "1.0"
serde_plain = "1.0"
wasm-bindgen = "0.2.50"

[dev-dependencies]
byteorder = "1.3.2"
